# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Zeynep/Desktop/projeVet_calisma/v.0.2/AB/vet.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 867)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{background-color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:reflect, x1:0.005, y1:0, x2:1, y2:0.636, stop:0.621891 rgba(0, 0, 0, 255), stop:1 rgba(38, 152, 159, 255));\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tablo = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tablo.setFont(font)
        self.tablo.setAcceptDrops(False)
        self.tablo.setAutoFillBackground(False)
        self.tablo.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(223, 223, 223);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(134, 134, 134);")
        self.tablo.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.tablo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tablo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tablo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tablo.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tablo.setAutoScroll(True)
        self.tablo.setAutoScrollMargin(16)
        self.tablo.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tablo.setTabKeyNavigation(True)
        self.tablo.setProperty("showDropIndicator", True)
        self.tablo.setDragEnabled(True)
        self.tablo.setDragDropOverwriteMode(True)
        self.tablo.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tablo.setAlternatingRowColors(False)
        self.tablo.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tablo.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablo.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tablo.setShowGrid(True)
        self.tablo.setGridStyle(QtCore.Qt.DotLine)
        self.tablo.setRowCount(100000)
        self.tablo.setColumnCount(30)
        self.tablo.setObjectName("tablo")
        self.tablo.horizontalHeader().setVisible(True)
        self.tablo.horizontalHeader().setCascadingSectionResizes(False)
        self.tablo.horizontalHeader().setHighlightSections(True)
        self.tablo.horizontalHeader().setSortIndicatorShown(False)
        self.tablo.horizontalHeader().setStretchLastSection(False)
        self.tablo.verticalHeader().setHighlightSections(True)
        self.gridLayout_2.addWidget(self.tablo, 1, 0, 1, 1)
        self.buton_geri = QtWidgets.QPushButton(self.centralwidget)
        self.buton_geri.setMinimumSize(QtCore.QSize(100, 50))
        self.buton_geri.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.buton_geri.setFont(font)
        self.buton_geri.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(105, 158, 158);")
        self.buton_geri.setObjectName("buton_geri")
        self.gridLayout_2.addWidget(self.buton_geri, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buton_ekle = QtWidgets.QPushButton(self.centralwidget)
        self.buton_ekle.setMinimumSize(QtCore.QSize(381, 61))
        self.buton_ekle.setMaximumSize(QtCore.QSize(381, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.buton_ekle.setFont(font)
        self.buton_ekle.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(179, 179, 179);")
        self.buton_ekle.setObjectName("buton_ekle")
        self.gridLayout.addWidget(self.buton_ekle, 7, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 2, 1, 1)
        self.buton_sil = QtWidgets.QPushButton(self.centralwidget)
        self.buton_sil.setMinimumSize(QtCore.QSize(381, 61))
        self.buton_sil.setMaximumSize(QtCore.QSize(381, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.buton_sil.setFont(font)
        self.buton_sil.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(179, 179, 179);")
        self.buton_sil.setObjectName("buton_sil")
        self.gridLayout.addWidget(self.buton_sil, 8, 1, 1, 1)
        self.buton_yukle = QtWidgets.QPushButton(self.centralwidget)
        self.buton_yukle.setMinimumSize(QtCore.QSize(381, 61))
        self.buton_yukle.setMaximumSize(QtCore.QSize(381, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.buton_yukle.setFont(font)
        self.buton_yukle.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(179, 179, 179);")
        self.buton_yukle.setObjectName("buton_yukle")
        self.gridLayout.addWidget(self.buton_yukle, 0, 1, 1, 1)
        self.buton_degistir = QtWidgets.QPushButton(self.centralwidget)
        self.buton_degistir.setMinimumSize(QtCore.QSize(381, 61))
        self.buton_degistir.setMaximumSize(QtCore.QSize(381, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.buton_degistir.setFont(font)
        self.buton_degistir.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(179, 179, 179);")
        self.buton_degistir.setObjectName("buton_degistir")
        self.gridLayout.addWidget(self.buton_degistir, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 934, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuYard_m = QtWidgets.QMenu(self.menuBar)
        self.menuYard_m.setObjectName("menuYard_m")
        MainWindow.setMenuBar(self.menuBar)
        self.actionVetSifreDegisim = QtWidgets.QAction(MainWindow)
        self.actionVetSifreDegisim.setObjectName("actionVetSifreDegisim")
        self.menuYard_m.addAction(self.actionVetSifreDegisim)
        self.menuBar.addAction(self.menuYard_m.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buton_geri.setText(_translate("MainWindow", "GERİ"))
        self.buton_ekle.setText(_translate("MainWindow", "YENİ KAYIT EKLE"))
        self.buton_sil.setText(_translate("MainWindow", "KAYIT SİL"))
        self.buton_yukle.setText(_translate("MainWindow", "DOSYA YÜKLE"))
        self.buton_degistir.setText(_translate("MainWindow", "DEĞİŞTİR"))
        self.menuYard_m.setTitle(_translate("MainWindow", "Yardım"))
        self.actionVetSifreDegisim.setText(_translate("MainWindow", "Şifre Değişimi"))

